# UNSPLIT_FILE="preprocess/subset/subset_1.json"
# PATH="features"

python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/V2_bal_subset_Functional_type_full ../too_big_for_git/models/Functional/V2_bal_subset_type_full/ALC_combo0_V2_bal_subset_type_full_Functional.pt Functional '{"lr":0.0001,"layers":[64,32,16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/V2_bal_subset_Functional_type_full ../too_big_for_git/models/Functional/V2_bal_subset_type_full/ALC_combo1_V2_bal_subset_type_full_Functional.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/V2_bal_subset_Functional_type_full ../too_big_for_git/models/Functional/V2_bal_subset_type_full/ALC_combo2_V2_bal_subset_type_full_Functional.pt Functional '{"lr":0.0001,"layers":[64,16,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/V2_bal_subset_Functional_type_full ../too_big_for_git/models/Functional/V2_bal_subset_type_full/ALC_combo3_V2_bal_subset_type_full_Functional.pt Functional '{"lr":0.0001,"layers":[64,32,16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":10,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/V2_bal_subset_Functional_type_full ../too_big_for_git/models/Functional/V2_bal_subset_type_full/ALC_combo4_V2_bal_subset_type_full_Functional.pt Functional '{"lr":0.0001,"layers":[64,32,16,8,4],"dropout":0.5,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/V2_bal_subset_Functional_type_full ../too_big_for_git/models/Functional/V2_bal_subset_type_full/ALC_combo5_V2_bal_subset_type_full_Functional.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":10,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/V2_bal_subset_Functional_type_full ../too_big_for_git/models/Functional/V2_bal_subset_type_full/ALC_combo6_V2_bal_subset_type_full_Functional.pt Functional '{"lr":0.0001,"layers":[64,32,16,8,4],"dropout":0,"optim":"SGD","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/V2_bal_subset_Functional_type_full ../too_big_for_git/models/Functional/V2_bal_subset_type_full/ALC_combo7_V2_bal_subset_type_full_Functional.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":10,"num_epochs":20,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/V2_bal_subset_Functional_type_full ../too_big_for_git/models/Functional/V2_bal_subset_type_full/ALC_combo8_V2_bal_subset_type_full_Functional.pt Functional '{"lr":0.00001,"layers":[64,32,16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/V2_bal_subset_Functional_type_full ../too_big_for_git/models/Functional/V2_bal_subset_type_full/ALC_combo9_V2_bal_subset_type_full_Functional.pt Functional '{"lr":0.0005,"layers":[64,32,16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/V2_bal_subset_Functional_type_full ../too_big_for_git/models/Functional/V2_bal_subset_type_full/ALC_combo10_V2_bal_subset_type_full_Functional.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":15,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/V2_bal_subset_Functional_type_full ../too_big_for_git/models/Functional/V2_bal_subset_type_full/ALC_combo11_V2_bal_subset_type_full_Functional.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0.1,"optim":"adam","bn":"True","batch_size":15,"num_epochs":10,"activation":"sigmoid"}'
