# python3 -u train_models.py  ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_LLD_normalised ../too_big_for_git/models/LLD/full_dataset/speaker_normalised/ALC_combo0_full_dataset_LLD_normalised.pt LLD '{"lr":0.0001,"layers":[16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"bidirectional":"False","bias":"True","lstm_layers":2,"activation":"sigmoid"}'
# python3 -u train_models.py  ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_LLD_normalised ../too_big_for_git/models/LLD/full_dataset/speaker_normalised/ALC_combo1_full_dataset_LLD_normalised.pt LLD '{"lr":0.0001,"layers":[8],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"bidirectional":"False","bias":"True","lstm_layers":2,"activation":"sigmoid"}'
# python3 -u train_models.py  ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_LLD_normalised ../too_big_for_git/models/LLD/full_dataset/speaker_normalised/ALC_combo2_full_dataset_LLD_normalised.pt LLD '{"lr":0.0001,"layers":[16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"bidirectional":"True","bias":"True","lstm_layers":2,"activation":"sigmoid"}'
# python3 -u train_models.py  ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_LLD_normalised ../too_big_for_git/models/LLD/full_dataset/speaker_normalised/ALC_combo3_full_dataset_LLD_normalised.pt LLD '{"lr":0.0001,"layers":[16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"bidirectional":"False","bias":"False","lstm_layers":2,"activation":"sigmoid"}'
# python3 -u train_models.py  ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_LLD_normalised ../too_big_for_git/models/LLD/full_dataset/speaker_normalised/ALC_combo4_full_dataset_LLD_normalised.pt LLD '{"lr":0.0001,"layers":[16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":10,"num_epochs":10,"bidirectional":"False","bias":"True","lstm_layers":2,"activation":"sigmoid"}'
# python3 -u train_models.py  ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_LLD_normalised ../too_big_for_git/models/LLD/full_dataset/speaker_normalised/ALC_combo5_full_dataset_LLD_normalised.pt LLD '{"lr":0.0001,"layers":[16,8,4],"dropout":0.5,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"bidirectional":"False","bias":"True","lstm_layers":2,"activation":"sigmoid"}'

# best combo 50/50
python3 -u train_models.py ../too_big_for_git/features/currently_used/filtered_class_balanced/filtered_features_balanced_LLD ../too_big_for_git/models/LLD/filtered_class_balanced_data/ALC_combo2_filtered_class_balanced_LLD_test.pt LLD '{"lr":0.0001,"layers":[16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"bidirectional":"True","bias":"True","lstm_layers":2,"activation":"sigmoid"}' --test

# best combo 50/50 normalised
python3 -u train_models.py ../too_big_for_git/features/currently_used/filtered_class_balanced/speaker_normalised/filtered_features_balanced_LLD_normalised ../too_big_for_git/models/LLD/filtered_class_balanced_data/speaker_normalised/ALC_combo4_filtered_class_balanced_LLD_normalised_test.pt LLD '{"lr":0.0001,"layers":[16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":10,"num_epochs":10,"bidirectional":"False","bias":"True","lstm_layers":2,"activation":"sigmoid"}' --test

# best combo bal. for C
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_full_orig_vt/V2_bal_subset_LLD_full ../too_big_for_git/models/LLD/V2_bal_subset_full/ALC_combo3_V2_bal_subset_full_LLD_test.pt LLD '{"lr":0.0001,"layers":[16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"bidirectional":"False","bias":"False","lstm_layers":2,"activation":"sigmoid"}' --test

# best combo bal. for C (norm.)
python3 -u train_models.py  ../too_big_for_git/features/currently_used/V2_full_orig_vt/speaker_normalised/V2_bal_subset_LLD_full_normalised ../too_big_for_git/models/LLD/V2_bal_subset_full/speaker_normalised/ALC_combo1_V2_bal_subset_full_LLD_normalised_test.pt LLD '{"lr":0.0001,"layers":[8],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"bidirectional":"False","bias":"True","lstm_layers":2,"activation":"sigmoid"}' --test

# best combo bal. for T
python3 -u train_models.py  ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/V2_bal_subset_LLD_type_full ../too_big_for_git/models/LLD/V2_bal_subset_type_full/ALC_combo1_V2_bal_subset_type_full_LLD_test.pt LLD '{"lr":0.0001,"layers":[8],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"bidirectional":"False","bias":"True","lstm_layers":2,"activation":"sigmoid"}' --test

# best combo bal. for T (norm.)
python3 -u train_models.py  ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/speaker_normalised/V2_bal_subset_LLD_type_full_normalised ../too_big_for_git/models/LLD/V2_bal_subset_type_full/speaker_normalised/ALC_combo1_V2_bal_subset_type_full_LLD_normalised_test.pt LLD '{"lr":0.0001,"layers":[8],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"bidirectional":"False","bias":"True","lstm_layers":2,"activation":"sigmoid"}' --test
