# UNSPLIT_FILE="preprocess/subset/subset_1.json"
# PATH="features"

python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/full_dataset_Functional ../too_big_for_git/models/Functional/full_dataset/ALC_combo0_full_dataset_Functional.pt Functional '{"lr":0.0001,"layers":[64,32,16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/full_dataset_Functional ../too_big_for_git/models/Functional/full_dataset/ALC_combo1_full_dataset_Functional.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/full_dataset_Functional ../too_big_for_git/models/Functional/full_dataset/ALC_combo2_full_dataset_Functional.pt Functional '{"lr":0.0001,"layers":[64,16,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/full_dataset_Functional ../too_big_for_git/models/Functional/full_dataset/ALC_combo3_full_dataset_Functional.pt Functional '{"lr":0.0001,"layers":[64,32,16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":10,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/full_dataset_Functional ../too_big_for_git/models/Functional/full_dataset/ALC_combo4_full_dataset_Functional.pt Functional '{"lr":0.0001,"layers":[64,32,16,8,4],"dropout":0.5,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/full_dataset_Functional ../too_big_for_git/models/Functional/full_dataset/ALC_combo5_full_dataset_Functional.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":10,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/full_dataset_Functional ../too_big_for_git/models/Functional/full_dataset/ALC_combo6_full_dataset_Functional.pt Functional '{"lr":0.0001,"layers":[64,32,16,8,4],"dropout":0,"optim":"SGD","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/full_dataset_Functional ../too_big_for_git/models/Functional/full_dataset/ALC_combo7_full_dataset_Functional.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":10,"num_epochs":20,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/full_dataset_Functional ../too_big_for_git/models/Functional/full_dataset/ALC_combo8_full_dataset_Functional.pt Functional '{"lr":0.00001,"layers":[64,32,16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/full_dataset_Functional ../too_big_for_git/models/Functional/full_dataset/ALC_combo9_full_dataset_Functional.pt Functional '{"lr":0.0005,"layers":[64,32,16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/full_dataset_Functional ../too_big_for_git/models/Functional/full_dataset/ALC_combo1__full_dataset_Functional.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":15,"num_epochs":10,"activation":"sigmoid"}'
python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/full_dataset_Functional ../too_big_for_git/models/Functional/full_dataset/ALC_combo1__full_dataset_Functional.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0.1,"optim":"adam","bn":"True","batch_size":15,"num_epochs":10,"activation":"sigmoid"}'
