# UNSPLIT_FILE="preprocess/subset/subset_1.json"
# PATH="features"

# python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_Functional_normalised ../too_big_for_git/models/Functional/full_dataset/speaker_normalised/ALC_combo0_full_dataset_Functional_normalised.pt Functional '{"lr":0.0001,"layers":[64,32,16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
# python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_Functional_normalised ../too_big_for_git/models/Functional/full_dataset/speaker_normalised/ALC_combo1_full_dataset_Functional_normalised.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
# python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_Functional_normalised ../too_big_for_git/models/Functional/full_dataset/speaker_normalised/ALC_combo2_full_dataset_Functional_normalised.pt Functional '{"lr":0.0001,"layers":[64,16,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
# python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_Functional_normalised ../too_big_for_git/models/Functional/full_dataset/speaker_normalised/ALC_combo3_full_dataset_Functional_normalised.pt Functional '{"lr":0.0001,"layers":[64,32,16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":10,"num_epochs":10,"activation":"sigmoid"}'
# python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_Functional_normalised ../too_big_for_git/models/Functional/full_dataset/speaker_normalised/ALC_combo4_full_dataset_Functional_normalised.pt Functional '{"lr":0.0001,"layers":[64,32,16,8,4],"dropout":0.5,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
# python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_Functional_normalised ../too_big_for_git/models/Functional/full_dataset/speaker_normalised/ALC_combo5_full_dataset_Functional_normalised.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":10,"num_epochs":10,"activation":"sigmoid"}'
# python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_Functional_normalised ../too_big_for_git/models/Functional/full_dataset/speaker_normalised/ALC_combo6_full_dataset_Functional_normalised.pt Functional '{"lr":0.0001,"layers":[64,32,16,8,4],"dropout":0,"optim":"SGD","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
# python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_Functional_normalised ../too_big_for_git/models/Functional/full_dataset/speaker_normalised/ALC_combo7_full_dataset_Functional_normalised.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":10,"num_epochs":20,"activation":"sigmoid"}'
# python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_Functional_normalised ../too_big_for_git/models/Functional/full_dataset/speaker_normalised/ALC_combo8_full_dataset_Functional_normalised.pt Functional '{"lr":0.00001,"layers":[64,32,16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
# python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_Functional_normalised ../too_big_for_git/models/Functional/full_dataset/speaker_normalised/ALC_combo9_full_dataset_Functional_normalised.pt Functional '{"lr":0.0005,"layers":[64,32,16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}'
# python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_Functional_normalised ../too_big_for_git/models/Functional/full_dataset/speaker_normalised/ALC_combo10_full_dataset_Functional_normalised.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":15,"num_epochs":10,"activation":"sigmoid"}'
# python3 -u train_models.py ../too_big_for_git/features/currently_used/full_dataset/speaker_normalised/full_dataset_Functional_normalised ../too_big_for_git/models/Functional/full_dataset/speaker_normalised/ALC_combo11_full_dataset_Functional_normalised.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0.1,"optim":"adam","bn":"True","batch_size":15,"num_epochs":10,"activation":"sigmoid"}'

# best combo 50/50
python3 -u train_models.py ../too_big_for_git/features/currently_used/filtered_class_balanced/filtered_features_balanced_Functional ../too_big_for_git/models/Functional/filtered_class_balanced_data/ALC_combo3_filtered_class_balanced_Functional_test.pt Functional '{"lr":0.0001,"layers":[64,32,16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":10,"num_epochs":10,"activation":"sigmoid"}' --test

# best combo 50/50 normalised
python3 -u train_models.py ../too_big_for_git/features/currently_used/filtered_class_balanced/speaker_normalised/filtered_features_balanced_Functional_normalised ../too_big_for_git/models/Functional/filtered_class_balanced_data/speaker_normalised/ALC_combo11_filtered_class_balanced_Functional_normalised_test.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0.1,"optim":"adam","bn":"True","batch_size":15,"num_epochs":10,"activation":"sigmoid"}' --test

# best combo bal. for C
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_full_orig_vt/V2_bal_subset_Functional_full ../too_big_for_git/models/Functional/V2_bal_subset_full/ALC_combo10_V2_bal_subset_full_Functional_test.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":15,"num_epochs":10,"activation":"sigmoid"}' --test

# best combo bal. for C (norm.)
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_full_orig_vt/speaker_normalised/V2_bal_subset_Functional_full_normalised ../too_big_for_git/models/Functional/V2_bal_subset_full/speaker_normalised/ALC_combo9_V2_bal_subset_full_Functional_normalised_test.pt Functional '{"lr":0.0005,"layers":[64,32,16,8,4],"dropout":0,"optim":"adam","bn":"True","batch_size":5,"num_epochs":10,"activation":"sigmoid"}' --test

# best combo bal. for T
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/V2_bal_subset_Functional_type_full ../too_big_for_git/models/Functional/V2_bal_subset_type_full/ALC_combo10_V2_bal_subset_type_full_Functional_test.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":15,"num_epochs":10,"activation":"sigmoid"}' --test

# best combo bal. for T (norm.)
python3 -u train_models.py ../too_big_for_git/features/currently_used/V2_type_full_orig_vt/speaker_normalised/V2_bal_subset_Functional_type_full_normalised ../too_big_for_git/models/Functional/V2_bal_subset_type_full/speaker_normalised/ALC_combo10_V2_bal_subset_type_full_Functional_normalised_test.pt Functional '{"lr":0.0001,"layers":[32],"dropout":0,"optim":"adam","bn":"True","batch_size":15,"num_epochs":10,"activation":"sigmoid"}' --test
